package hust.soict.ict.flashcard_web.entity;

import jakarta.persistence.*;
import java.util.List;
import java.time.LocalDateTime;

/**
 * Represents a deck of flashcards in the database.
 * Each deck is associated with a user and contains multiple flashcards.
 */
@Entity
@Table(name = "decks")
public class DeckEntity {

    /**
     * The unique identifier for the deck.
     * It is automatically generated by the database.
     */
    @Id
    @Column(name = "deck_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * A list of flashcards that belong to this deck.
     * This is a one-to-many relationship, where one deck can have many flashcards.
     * `mappedBy = "deck"` indicates that the `FlashcardEntity` class owns the relationship.
     * `cascade = CascadeType.ALL` means that operations (persist, remove, etc.) on a deck will propagate to its flashcards.
     * `orphanRemoval = true` ensures that if a flashcard is removed from this list, it is also deleted from the database.
     */
    @OneToMany(mappedBy = "deck", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<FlashcardEntity> flashcards;

    /**
     * The user who owns this deck.
     * This is a many-to-one relationship, where many decks can belong to a single user.
     * The `user_id` column in the `decks` table is a foreign key referencing the `users` table.
     */
    @ManyToOne
    @JoinColumn(name = "user_id",  nullable = false)
    private UserEntity user;

    /**
     * The title of the deck.
     * This field cannot be null.
     */
    @Column(name = "title", nullable = false)
    private String title;

    /**
     * A detailed description of the deck.
     * The `columnDefinition = "TEXT"` is used for potentially long string content.
     */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    /**
     * The timestamp when the deck was created.
     * This field is managed by the database and is not updatable or insertable from the application.
     */
    @Column(name = "created_at", nullable = false, updatable = false, insertable = false)
    private LocalDateTime createdAt;

    /**
     * Default constructor required by JPA.
     */
    public DeckEntity() {}

    // Getters and Setters

    /**
     * @return the unique identifier of the deck.
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the unique identifier to set for the deck.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return the user who owns the deck.
     */
    public UserEntity getUser() {
        return user;
    }

    /**
     * @param user the user to associate with the deck.
     */
    public void setUser(UserEntity user) {
        this.user = user;
    }

    /**
     * @return the title of the deck.
     */
    public String getTitle() {
        return title;
    }

    /**
     * @param title the title to set for the deck.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * @return the description of the deck.
     */
    public String getDescription() {
        return description;
    }

    /**
     * @param description the description to set for the deck.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * @return the creation timestamp of the deck.
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * @return the list of flashcards associated with the deck.
     */
    public List<FlashcardEntity> getFlashcards () {
        return flashcards;
    }

    /**
     * @param flashcards the list of flashcards to associate with the deck.
     */
    public void setFlashcards (List<FlashcardEntity> flashcards) {
        this.flashcards = flashcards;
    }

}
